// Small canonical mapping for special-case Pokémon names to PokeAPI slugs
export const CANONICAL_NAME_MAP: Record<string, string> = {
  "nidoran (female)": "nidoran-f",
  "nidoran (male)": "nidoran-m",
  "farfetch'd": "farfetchd",
  "mr. mime": "mr-mime",
  "mr mime": "mr-mime",
  "mime jr.": "mime-jr",
  "mime jr": "mime-jr",
  "flabébé": "flabebe",
  "sirfetch'd": "sirfetchd",
  "porygon-z": "porygon-z",
  // Paldea & Paradox / Iron forms common slugs
  "great tusk": "great-tusk",
  "scream tail": "scream-tail",
  "brute bonnet": "brute-bonnet",
  "flutter mane": "flutter-mane",
  "slither wing": "slither-wing",
  "sandy shocks": "sandy-shocks",
  "iron treads": "iron-treads",
  "iron bundle": "iron-bundle",
  "iron hands": "iron-hands",
  "iron jugulis": "iron-jugulis",
  "iron moth": "iron-moth",
  "iron thorns": "iron-thorns",
  "iron valiant": "iron-valiant",
  "iron boulder": "iron-boulder",
  "iron crown": "iron-crown",
  "roaring moon": "roaring-moon",
  "walking wake": "walking-wake",
  "koraidon": "koraidon",
  "miraidon": "miraidon",
  "wo-chien": "wo-chien",
  "chien-pao": "chien-pao",
  "ting-lu": "ting-lu",
  "chi-yu": "chi-yu",
  "flabebe": "flabebe",
};

export default CANONICAL_NAME_MAP;
